import { erp } from './firebase.js';
import { $, esc, money, number, getFormData, toast, table, statusBadge, renderTabs, attachTabs, exportCSV } from './utils.js';
import { roleLabel } from './permissions.js';

export async function renderEmployees(root, user) {
  const [users, advances, salaries, expenses, counts] = await Promise.all([erp.list(`users`,{includeDeleted:true}), erp.list(`employeeAdvances`), erp.list(`salaries`), erp.list(`vehicleExpenses`), erp.list(`stockCounts`)]);
  root.innerHTML = `<section class="card">${renderTabs([{id:`directory`,label:`دليل الموظفين`},{id:`statement`,label:`كشف موظف`}],`directory`)}
    <div class="panel active" data-panel="directory">${directory(users)}</div>
    <div class="panel" data-panel="statement">${statement(users, advances, salaries, expenses, counts)}</div>
  </section>`;
  attachTabs(root);
  bindEmployees(root, users);
}
function directory(users){ return `<div class="actions"><button class="btn primary" id="newEmployeeBtn">إضافة موظف</button><button class="btn" id="exportEmployeesBtn">تصدير الموظفين</button></div><br>${table([{label:`الاسم`,value:`fullName`},{label:`الدور`,value:r=>roleLabel(r.role)},{label:`تاريخ البداية`,value:`startDate`},{label:`الراتب`,value:r=>money(r.normalMonthlySalary)},{label:`المستودع`,value:`assignedWarehouseId`},{label:`النقد`,value:r=>money(r.cashBalance)},{label:`السلف`,value:r=>money(r.advancesBalance)},{label:`الحالة`,value:r=>statusBadge(r.status)},{label:`إجراء`,value:r=>`<button class="btn" data-edit-employee="${esc(r.id)}">تعديل</button>`}],users,`لا يوجد موظفون`)}`; }
function statement(users, advances, salaries, expenses, counts){ return `<label>اختر الموظف<select id="employeeStatementSelect"><option value="">اختر</option>${users.map(u=>`<option value="${esc(u.id)}">${esc(u.fullName)}</option>`).join(``)}</select></label><div id="employeeStatement" style="margin-top:14px"><div class="empty">اختر موظفاً لعرض الكشف المالي والتشغيلي.</div></div>`; }
function employeeForm(emp={}){ return `<form id="employeeForm" class="form-grid"><input type="hidden" name="id" value="${esc(emp.id||``)}"><label>الاسم الكامل<input name="fullName" required value="${esc(emp.fullName||``)}"></label><label>البريد<input name="email" type="email" value="${esc(emp.email||``)}"></label><label>اسم المستخدم<input name="username" value="${esc(emp.username||``)}"></label><label>الدور<input name="role" value="${esc(emp.role||`sales_rep`)}"></label><label>تاريخ البداية<input name="startDate" type="date" value="${esc(emp.startDate||``)}"></label><label>الراتب الشهري<input name="normalMonthlySalary" type="number" step="0.001" value="${number(emp.normalMonthlySalary)}"></label><label>المستودع المخصص<input name="assignedWarehouseId" value="${esc(emp.assignedWarehouseId||``)}"></label><label>الحالة<select name="status"><option value="active" ${emp.status!==`inactive`?`selected`:``}>فعال</option><option value="inactive" ${emp.status===`inactive`?`selected`:``}>غير فعال</option></select></label><label class="wide">ملاحظات<textarea name="notes">${esc(emp.notes||``)}</textarea></label></form>`; }
function bindEmployees(root, users){ root.addEventListener(`click`,async e=>{ if(e.target.closest(`#newEmployeeBtn`)) showEmp(); const edit=e.target.closest(`[data-edit-employee]`); if(edit) showEmp(await erp.get(`users`,edit.dataset.editEmployee)); if(e.target.closest(`#exportEmployeesBtn`)) exportCSV(`employees.csv`, await erp.list(`users`,{includeDeleted:true})); }); root.addEventListener(`change`,async e=>{ if(e.target.id===`employeeStatementSelect`){ const id=e.target.value; const emp=users.find(u=>u.id===id); if(!emp){ $(`#employeeStatement`).innerHTML=`<div class="empty">اختر موظفاً</div>`; return; } const [adv,sal,exp,cnt]=await Promise.all([erp.list(`employeeAdvances`),erp.list(`salaries`),erp.list(`vehicleExpenses`),erp.list(`stockCounts`)]); $(`#employeeStatement`).innerHTML=`<div class="grid four"><section class="card kpi"><div><div class="label">النقد</div><div class="num">${money(emp.cashBalance)}</div></div></section><section class="card kpi"><div><div class="label">CliQ</div><div class="num">${money(emp.cliqBalance)}</div></div></section><section class="card kpi"><div><div class="label">السلف</div><div class="num">${money(emp.advancesBalance)}</div></div></section><section class="card kpi"><div><div class="label">الراتب</div><div class="num">${money(emp.normalMonthlySalary)}</div></div></section></div><br><h3>السلف والاقتطاعات</h3>${table([{label:`التاريخ`,value:`date`},{label:`المصدر`,value:`source`},{label:`المبلغ`,value:r=>money(r.amount)},{label:`ملاحظات`,value:`notes`}],adv.filter(x=>x.employeeId===id))}<br><h3>الرواتب</h3>${table([{label:`الشهر`,value:`salaryMonth`},{label:`الأساسي`,value:r=>money(r.baseSalary)},{label:`السلف`,value:r=>money(r.advancesDeducted)},{label:`الصافي`,value:r=>money(r.netSalary)}],sal.filter(x=>x.employeeId===id))}<br><h3>مصاريف السيارة</h3>${table([{label:`التاريخ`,value:`date`},{label:`النوع`,value:`expenseType`},{label:`المبلغ`,value:r=>money(r.amount)},{label:`الجهة`,value:`vendor`}],exp.filter(x=>x.repId===id))}`; } }); async function showEmp(emp={}){ const {modal}=await import('./utils.js'); modal(emp.id?`تعديل موظف`:`إضافة موظف`,employeeForm(emp),[{label:`حفظ`,className:`primary`,handler:async wrap=>{const f=$(`#employeeForm`,wrap); if(!f.reportValidity()) return; const d=getFormData(f); const payload={...d,normalMonthlySalary:number(d.normalMonthlySalary)}; if(d.id) await erp.update(`users`,d.id,payload); else await erp.add(`users`,payload); wrap.remove(); toast(`تم حفظ بيانات الموظف`); location.reload();}}]); } }
