import { erp } from './firebase.js';
import { $, esc, money, number, uid, todayISO, getFormData, toast, table, statusBadge, renderTabs, attachTabs, exportCSV } from './utils.js';
import { can } from './permissions.js';

export async function renderFinance(root, user) {
  const [users, deliveries, transfers, advances, salaries, expenses] = await Promise.all([erp.list(`users`), erp.list(`cashDeliveries`), erp.list(`internalTransfers`), erp.list(`employeeAdvances`), erp.list(`salaries`), erp.list(`vehicleExpenses`)]);
  root.innerHTML = `<section class="card">${renderTabs([{id:`delivery`,label:`تسليم نقد`},{id:`confirm`,label:`تأكيد الاستلام`},{id:`transfer`,label:`تحويل داخلي`},{id:`advances`,label:`السلف`},{id:`salaries`,label:`الرواتب`},{id:`expenses`,label:`مصروف سيارة`}],`delivery`)}
    <div class="panel active" data-panel="delivery">${deliveryPanel(users, user)}</div>
    <div class="panel" data-panel="confirm">${confirmPanel(deliveries)}</div>
    <div class="panel" data-panel="transfer">${transferPanel(users)}</div>
    <div class="panel" data-panel="advances">${advancesPanel(users, advances)}</div>
    <div class="panel" data-panel="salaries">${salariesPanel(users, salaries)}</div>
    <div class="panel" data-panel="expenses">${expensesPanel(users, expenses)}</div>
  </section>`;
  attachTabs(root);
  bindFinance(root, users, deliveries, user);
}
function deliveryPanel(users,user){ const receivers=users.filter(u=>[`dawood`,`moatasem`,`admin`,`finance_user`].includes(u.role)); return `<form id="deliveryForm" class="form-grid"><label>رقم التسليم<input name="deliveryNumber" value="${uid(`DEL`)}" readonly></label><label>التاريخ<input name="date" type="date" value="${todayISO()}"></label><label>المرسل<select name="senderId">${users.map(u=>`<option value="${esc(u.id)}" ${u.id===user.id?`selected`:``}>${esc(u.fullName)}</option>`).join(``)}</select></label><label>المستلم<select name="receiverId">${receivers.map(u=>`<option value="${esc(u.id)}">${esc(u.fullName)}</option>`).join(``)}</select></label><label>النوع<select name="deliveryType"><option value="cash">نقد</option><option value="cliq">CliQ</option><option value="bank">تحويل بنكي</option></select></label><label>المبلغ<input name="amount" type="number" min="0.001" step="0.001" required></label><label class="wide">ملاحظات<textarea name="notes"></textarea></label><button class="btn primary" type="submit">إرسال طلب التسليم</button></form>`; }
function confirmPanel(deliveries){ return `<div class="actions"><button class="btn" id="exportDeliveriesBtn">تصدير التسليمات</button></div><br>${table([{label:`رقم`,value:`deliveryNumber`},{label:`المرسل`,value:`senderName`},{label:`المستلم`,value:`receiverName`},{label:`النوع`,value:`deliveryType`},{label:`المبلغ`,value:r=>money(r.amount)},{label:`الحالة`,value:r=>statusBadge(r.status)},{label:`إجراء`,value:r=>r.status===`pending`?`<button class="btn green" data-confirm-delivery="${esc(r.id)}">تأكيد</button> <button class="btn danger" data-reject-delivery="${esc(r.id)}">رفض</button>`:`—`}],deliveries,`لا توجد تسليمات`)}`; }
function transferPanel(users){ return `<form id="transferForm" class="form-grid"><label>رقم التحويل<input name="transferNumber" value="${uid(`TRN`)}" readonly></label><label>التاريخ<input name="date" type="date" value="${todayISO()}"></label><label>من مستخدم<select name="senderId">${users.map(u=>`<option value="${esc(u.id)}">${esc(u.fullName)}</option>`).join(``)}</select></label><label>إلى مستخدم<select name="receiverId">${users.map(u=>`<option value="${esc(u.id)}">${esc(u.fullName)}</option>`).join(``)}</select></label><label>نوع الرصيد<select name="balanceField"><option value="cashBalance">نقد</option><option value="cliqBalance">CliQ</option></select></label><label>المبلغ<input name="amount" type="number" min="0.001" step="0.001" required></label><label class="wide">ملاحظات<textarea name="notes"></textarea></label><button class="btn primary" type="submit">اعتماد التحويل</button></form>`; }
function advancesPanel(users, advances){ return `<form id="advanceForm" class="form-grid"><label>الموظف<select name="employeeId">${users.map(u=>`<option value="${esc(u.id)}">${esc(u.fullName)}</option>`).join(``)}</select></label><label>التاريخ<input name="date" type="date" value="${todayISO()}"></label><label>المصدر<select name="source"><option value="cash_advance">سلفة نقدية</option><option value="stock_shortage">نقص جرد</option><option value="deduction">اقتطاع</option><option value="other">أخرى</option></select></label><label>المبلغ<input name="amount" type="number" min="0.001" step="0.001" required></label><label class="wide">ملاحظات<textarea name="notes"></textarea></label><button class="btn primary" type="submit">تسجيل السلفة</button></form><br>${table([{label:`الموظف`,value:r=>esc(users.find(u=>u.id===r.employeeId)?.fullName||`—`)},{label:`المصدر`,value:`source`},{label:`المبلغ`,value:r=>money(r.amount)},{label:`التاريخ`,value:`date`},{label:`الحالة`,value:r=>statusBadge(r.status)}],advances,`لا توجد سلف`)}`; }
function salariesPanel(users,salaries){ return `<form id="salaryForm" class="form-grid"><label>الشهر<input name="salaryMonth" type="month" value="${todayISO().slice(0,7)}"></label><label>الموظف<select name="employeeId">${users.map(u=>`<option value="${esc(u.id)}">${esc(u.fullName)}</option>`).join(``)}</select></label><label>مكافآت/بدلات<input name="bonus" type="number" step="0.001" value="0"></label><label>اقتطاعات إضافية<input name="deductions" type="number" step="0.001" value="0"></label><label class="wide">ملاحظات<textarea name="notes"></textarea></label><button class="btn primary" type="submit">احتساب وصرف الراتب</button></form><br>${table([{label:`الشهر`,value:`salaryMonth`},{label:`الموظف`,value:`employeeName`},{label:`الراتب`,value:r=>money(r.baseSalary)},{label:`السلف`,value:r=>money(r.advancesDeducted)},{label:`الصافي`,value:r=>money(r.netSalary)},{label:`الحالة`,value:r=>statusBadge(r.status)},{label:`طباعة`,value:r=>`<button class="btn" data-print-salary="${esc(r.id)}">قسيمة</button>`}],salaries,`لا توجد رواتب`)}`; }
function expensesPanel(users,expenses){ return `<form id="expenseForm" class="form-grid"><label>المندوب<select name="repId">${users.filter(u=>u.role===`sales_rep`).map(u=>`<option value="${esc(u.id)}">${esc(u.fullName)}</option>`).join(``)}</select></label><label>التاريخ<input name="date" type="date" value="${todayISO()}"></label><label>نوع المصروف<select name="expenseType"><option value="tool">أداة</option><option value="maintenance">صيانة سيارة</option><option value="fuel">محروقات</option><option value="misc">متفرقات</option></select></label><label>المبلغ<input name="amount" type="number" min="0.001" step="0.001" required></label><label>المورد/الجهة<input name="vendor"></label><label>حالة الاعتماد<select name="approvalStatus"><option value="pending">بانتظار المراجعة</option><option value="approved">معتمد</option></select></label><label class="wide">ملاحظات<textarea name="notes"></textarea></label><button class="btn primary" type="submit">حفظ مصروف السيارة</button></form><br>${table([{label:`المندوب`,value:r=>esc(users.find(u=>u.id===r.repId)?.fullName||`—`)},{label:`النوع`,value:`expenseType`},{label:`المبلغ`,value:r=>money(r.amount)},{label:`الجهة`,value:`vendor`},{label:`الحالة`,value:r=>statusBadge(r.approvalStatus||r.status)}],expenses,`لا توجد مصاريف سيارات`)}`; }
function bindFinance(root, users, deliveries, user){
  $(`#deliveryForm`,root)?.addEventListener(`submit`,async e=>{ e.preventDefault(); const d=getFormData(e.target); const sender=users.find(u=>u.id===d.senderId), receiver=users.find(u=>u.id===d.receiverId); const field=d.deliveryType===`cliq`?`cliqBalance`:`cashBalance`; if(number(sender[field])<number(d.amount) && !can(user,`finance`)) return toast(`لا يوجد رصيد كافي للتسليم`,`err`); await erp.add(`cashDeliveries`,{...d,amount:number(d.amount),senderName:sender.fullName,receiverName:receiver.fullName,status:`pending`}); toast(`تم إرسال طلب التسليم وبانتظار تأكيد الاستلام`); location.reload(); });
  $(`#transferForm`,root)?.addEventListener(`submit`,async e=>{ e.preventDefault(); const d=getFormData(e.target); const amount=number(d.amount); await erp.adjustUserBalance(d.senderId,d.balanceField,-amount,`تحويل داخلي صادر`); await erp.adjustUserBalance(d.receiverId,d.balanceField,amount,`تحويل داخلي وارد`); await erp.add(`internalTransfers`,{...d,amount,status:`confirmed`}); toast(`تم اعتماد التحويل الداخلي`); location.reload(); });
  $(`#advanceForm`,root)?.addEventListener(`submit`,async e=>{ e.preventDefault(); const d=getFormData(e.target); const amount=number(d.amount); await erp.add(`employeeAdvances`,{...d,amount,status:`confirmed`}); await erp.adjustUserBalance(d.employeeId,`advancesBalance`,amount,`تسجيل سلفة`); toast(`تم تسجيل السلفة`); location.reload(); });
  $(`#salaryForm`,root)?.addEventListener(`submit`,async e=>{ e.preventDefault(); const d=getFormData(e.target); const emp=users.find(u=>u.id===d.employeeId); const base=number(emp.normalMonthlySalary); const advances=number(emp.advancesBalance); const net=base+number(d.bonus)-number(d.deductions)-advances; await erp.add(`salaries`,{...d,employeeName:emp.fullName,baseSalary:base,advancesDeducted:advances,netSalary:net,status:`paid`,date:todayISO()}); await erp.update(`users`,emp.id,{advancesBalance:0}); toast(`تم احتساب وصرف الراتب`); location.reload(); });
  $(`#expenseForm`,root)?.addEventListener(`submit`,async e=>{ e.preventDefault(); const d=getFormData(e.target); const amount=number(d.amount); await erp.add(`vehicleExpenses`,{...d,amount,status:d.approvalStatus}); await erp.adjustUserBalance(d.repId,`cashBalance`,-amount,`مصروف سيارة`); toast(`تم حفظ مصروف السيارة`); location.reload(); });
  root.addEventListener(`click`,async e=>{ const c=e.target.closest(`[data-confirm-delivery]`); const r=e.target.closest(`[data-reject-delivery]`); if(c){ const d=deliveries.find(x=>x.id===c.dataset.confirmDelivery); const field=d.deliveryType===`cliq`?`cliqBalance`:`cashBalance`; await erp.adjustUserBalance(d.senderId,field,-number(d.amount),`تسليم نقد مؤكد`,d.id); await erp.adjustUserBalance(d.receiverId,field,number(d.amount),`استلام نقد مؤكد`,d.id); await erp.update(`cashDeliveries`,d.id,{status:`confirmed`,confirmedAt:new Date().toISOString(),confirmedBy:user.id}); toast(`تم تأكيد الاستلام`); location.reload(); } if(r){ const d=deliveries.find(x=>x.id===r.dataset.rejectDelivery); await erp.update(`cashDeliveries`,d.id,{status:`rejected`,rejectedAt:new Date().toISOString(),rejectedBy:user.id}); toast(`تم رفض التسليم`,`warn`); location.reload(); } if(e.target.closest(`#exportDeliveriesBtn`)) exportCSV(`cash-deliveries.csv`, await erp.list(`cashDeliveries`)); });
}
