import { erp } from './firebase.js';
import { $, esc, money, qty, number, uid, todayISO, getFormData, toast, table, statusBadge, lineBuilder, exportExcel, renderTabs, attachTabs } from './utils.js';

export async function renderPurchases(root, user) {
  const [items, suppliers, purchases, debts] = await Promise.all([erp.list(`items`), erp.list(`suppliers`), erp.list(`purchaseInvoices`), erp.list(`supplierDebts`)]);
  root.innerHTML = `<section class="card">${renderTabs([{id:`purchase`,label:`فاتورة شراء`},{id:`suppliers`,label:`الموردون`},{id:`payables`,label:`ذمم الموردين`},{id:`history`,label:`سجل المشتريات`}],`purchase`)}
    <div class="panel active" data-panel="purchase">${purchasePanel(suppliers)}</div>
    <div class="panel" data-panel="suppliers">${suppliersPanel(suppliers)}</div>
    <div class="panel" data-panel="payables">${payablesPanel(debts)}</div>
    <div class="panel" data-panel="history">${historyPanel(purchases, suppliers)}</div>
  </section>`;
  attachTabs(root);
  bindPurchase(root, items, suppliers, user);
  bindSuppliers(root);
  bindPayments(root, debts);
}
function purchasePanel(suppliers){ return `<form id="purchaseForm" class="form-grid"><label>رقم الشراء<input name="purchaseNumber" value="${uid(`PUR`)}" readonly></label><label>التاريخ<input name="date" type="date" value="${todayISO()}"></label><label>المورد<select name="supplierId" required>${suppliers.map(s=>`<option value="${esc(s.id)}">${esc(s.supplierName)}</option>`).join(``)}</select></label><label>نوع الدفع<select name="paymentType"><option value="cash">نقدي</option><option value="credit">ذمم مورد</option></select></label><label>المبلغ المدفوع<input name="paidAmount" type="number" min="0" step="0.001" value="0"></label><label>المستودع المستلم<input name="warehouseId" value="main" readonly></label><label class="wide">ملاحظات<textarea name="notes"></textarea></label></form><div id="purchaseLines" style="margin-top:14px"></div><div class="actions" style="margin-top:14px"><button class="btn primary" id="confirmPurchaseBtn">اعتماد الشراء</button></div>`; }
function suppliersPanel(suppliers){ return `<div class="actions"><button class="btn primary" id="newSupplierBtn">إضافة مورد</button><button class="btn" id="exportSuppliersBtn">تصدير الموردين</button></div><br>${table([{label:`المورد`,value:`supplierName`},{label:`الهاتف`,value:`phone`},{label:`العنوان`,value:`address`},{label:`الرصيد`,value:r=>money(r.currentBalance)},{label:`الحالة`,value:r=>statusBadge(r.status)}],suppliers,`لا يوجد موردون`)}`; }
function payablesPanel(debts){ return `<div class="actions"><button class="btn" id="exportPayablesBtn">تصدير ذمم الموردين</button></div><br>${table([{label:`المورد`,value:`supplierName`},{label:`فاتورة`,value:`purchaseNumber`},{label:`الأصل`,value:r=>money(r.originalAmount)},{label:`المدفوع`,value:r=>money(r.paidAmount)},{label:`المتبقي`,value:r=>money(r.remainingAmount)},{label:`الحالة`,value:r=>statusBadge(r.status)},{label:`دفع`,value:r=>`<button class="btn green" data-pay-supplier="${esc(r.id)}">تسجيل دفعة</button>`}],debts.filter(d=>d.status!==`paid`),`لا توجد ذمم موردين مفتوحة`)}`; }
function historyPanel(purchases,suppliers){ return `<div class="actions"><button class="btn" id="exportPurchasesBtn">تصدير المشتريات</button></div><br>${table([{label:`رقم`,value:`purchaseNumber`},{label:`التاريخ`,value:`date`},{label:`المورد`,value:r=>esc(suppliers.find(s=>s.id===r.supplierId)?.supplierName||`—`)},{label:`الإجمالي`,value:r=>money(r.total)},{label:`الدفع`,value:r=>r.paymentType===`cash`?`نقدي`:`ذمم`},{label:`الحالة`,value:r=>statusBadge(r.status)}],purchases,`لا توجد مشتريات`)}`; }
function supplierForm(){ return `<form id="supplierForm" class="form-grid"><label>اسم المورد<input name="supplierName" required></label><label>الهاتف<input name="phone" inputmode="tel"></label><label>العنوان<input name="address"></label><label>رصيد افتتاحي<input name="openingBalance" type="number" step="0.001" value="0"></label><label>الحالة<select name="status"><option value="active">فعال</option><option value="inactive">غير فعال</option></select></label><label class="wide">ملاحظات<textarea name="notes"></textarea></label></form>`; }
function bindPurchase(root, items, suppliers, user){ let lines=[]; lineBuilder($(`#purchaseLines`,root),items,l=>lines=l); $(`#confirmPurchaseBtn`,root)?.addEventListener(`click`,async()=>{ const form=$(`#purchaseForm`,root); if(!form.reportValidity())return; if(!lines.length)return toast(`أدخل صنفاً واحداً على الأقل`,`err`); const d=getFormData(form); const supplier=suppliers.find(s=>s.id===d.supplierId); const total=lines.reduce((s,l)=>s+number(l.quantity)*number(l.price),0); const paid=number(d.paidAmount); const remaining=Math.max(0,total-paid); const inv=await erp.add(`purchaseInvoices`,{...d,supplierName:supplier?.supplierName||``,items:lines,total,paidAmount:paid,remainingAmount:remaining,status:`confirmed`}); for(const line of lines){ await erp.changeStock(line.itemId,d.warehouseId,number(line.quantity),`فاتورة شراء`,{purchaseNumber:d.purchaseNumber,purchaseId:inv.id}); const item=await erp.get(`items`,line.itemId); await erp.update(`items`,line.itemId,{costPrice:number(line.price),stock:item.stock}); } if(d.paymentType===`credit` && remaining>0){ await erp.add(`supplierDebts`,{supplierId:d.supplierId,supplierName:supplier?.supplierName||``,purchaseId:inv.id,purchaseNumber:d.purchaseNumber,originalAmount:total,paidAmount:paid,remainingAmount:remaining,status:`open`}); await erp.update(`suppliers`,d.supplierId,{currentBalance:number(supplier?.currentBalance)+remaining}); } if(d.paymentType===`cash` || paid>0){ await erp.adjustUserBalance(user.id,`cashBalance`,-paid,`دفع مشتريات`,inv.id); } toast(`تم اعتماد فاتورة الشراء`); location.reload(); }); }
function bindSuppliers(root){ root.addEventListener(`click`,async e=>{ if(e.target.closest(`#newSupplierBtn`)){ const {modal}=await import('./utils.js'); modal(`إضافة مورد`,supplierForm(),[{label:`حفظ`,className:`primary`,handler:async wrap=>{const f=$(`#supplierForm`,wrap); if(!f.reportValidity())return; const d=getFormData(f); await erp.add(`suppliers`,{...d,openingBalance:number(d.openingBalance),currentBalance:number(d.openingBalance)}); wrap.remove(); toast(`تم حفظ المورد`); location.reload();}}]); } if(e.target.closest(`#exportSuppliersBtn`)) exportExcel(`suppliers.xls`, await erp.list(`suppliers`)); if(e.target.closest(`#exportPurchasesBtn`)) exportExcel(`purchases.xls`, await erp.list(`purchaseInvoices`)); if(e.target.closest(`#exportPayablesBtn`)) exportExcel(`supplier-payables.xls`, await erp.list(`supplierDebts`)); }); }
function bindPayments(root,debts){ root.addEventListener(`click`,async e=>{ const btn=e.target.closest(`[data-pay-supplier]`); if(!btn)return; const debt=debts.find(d=>d.id===btn.dataset.paySupplier); const {modal}=await import('./utils.js'); modal(`تسجيل دفعة لمورد`, `<form id="supplierPaymentForm" class="form-grid two"><label>المبلغ<input name="amount" type="number" min="0.001" step="0.001" max="${number(debt.remainingAmount)}" required></label><label>طريقة الدفع<select name="method"><option value="cash">نقد</option><option value="bank">تحويل بنكي</option></select></label><label class="wide">ملاحظات<textarea name="notes"></textarea></label></form>`,[{label:`حفظ الدفعة`,className:`green`,handler:async wrap=>{const f=$(`#supplierPaymentForm`,wrap); if(!f.reportValidity())return; const d=getFormData(f); const amount=number(d.amount); const remaining=number(debt.remainingAmount)-amount; await erp.update(`supplierDebts`,debt.id,{paidAmount:number(debt.paidAmount)+amount,remainingAmount:remaining,status:remaining<=0?`paid`:`partial`}); await erp.add(`purchaseInvoices`,{purchaseNumber:uid(`PAY`),supplierId:debt.supplierId,supplierName:debt.supplierName,date:todayISO(),items:[],total:amount,paidAmount:amount,paymentType:`supplier_payment`,notes:d.notes,status:`confirmed`}); wrap.remove(); toast(`تم تسجيل دفعة المورد`); location.reload();}}]); }); }
