import { erp } from './firebase.js';
import { $, esc, money, qty, number, uid, todayISO, getFormData, toast, table, statusBadge, lineBuilder, exportCSV, renderTabs, attachTabs } from './utils.js';

export async function renderSales(root, user) {
  const [items, customers, reps, invoices, debts, collections] = await Promise.all([erp.list(`items`), erp.list(`customers`), erp.list(`users`), erp.list(`salesInvoices`), erp.list(`customerDebts`), erp.list(`collections`)]);
  root.innerHTML = `<section class="card">${renderTabs([{id:`invoice`,label:`فاتورة بيع`},{id:`customers`,label:`العملاء`},{id:`debts`,label:`ذمم العملاء`},{id:`history`,label:`الفواتير`}],`invoice`)}
    <div class="panel active" data-panel="invoice">${invoicePanel(customers, reps, user)}</div>
    <div class="panel" data-panel="customers">${customersPanel(customers, reps)}</div>
    <div class="panel" data-panel="debts">${debtsPanel(debts, collections)}</div>
    <div class="panel" data-panel="history">${historyPanel(invoices, customers, reps)}</div>
  </section>`;
  attachTabs(root);
  bindInvoice(root, items, customers, reps, user);
  bindCustomers(root, reps);
  bindCollections(root, debts, user);
}
function invoicePanel(customers, reps, user){ return `<form id="salesForm" class="form-grid"><label>رقم الفاتورة<input name="invoiceNumber" value="${uid(`SAL`)}" readonly></label><label>التاريخ<input name="date" type="date" value="${todayISO()}"></label><label>البائع<select name="sellerId" required>${reps.filter(u=>[`sales_rep`,`dawood`,`moatasem`,`admin`].includes(u.role)).map(r=>`<option value="${esc(r.id)}" ${user.id===r.id?`selected`:``}>${esc(r.fullName)}</option>`).join(``)}</select></label><label>العميل<select name="customerId" required>${customers.map(c=>`<option value="${esc(c.id)}">${esc(c.customerName)}</option>`).join(``)}</select></label><label>نوع البيع<select name="saleType"><option value="cash">نقدي</option><option value="credit">ذمم / آجل</option></select></label><label>المبلغ المدفوع<input name="paidAmount" type="number" min="0" step="0.001" value="0"></label><label>تاريخ الاستحقاق<input name="dueDate" type="date"></label><label class="wide">ملاحظات<textarea name="notes"></textarea></label></form><div id="salesLines" style="margin-top:14px"></div><div class="actions" style="margin-top:14px"><button class="btn primary" id="confirmSaleBtn">اعتماد الفاتورة</button><button class="btn" id="draftSaleBtn">حفظ كمسودة</button></div>`; }
function customersPanel(customers, reps){ return `<div class="actions"><button class="btn primary" id="newCustomerBtn">إضافة عميل</button><button class="btn" id="exportCustomersBtn">تصدير العملاء</button></div><br>${table([{label:`العميل`,value:`customerName`},{label:`الهاتف`,value:`phone`},{label:`المنطقة`,value:`area`},{label:`المندوب`,value:r=>esc(reps.find(u=>u.id===r.responsibleRepId)?.fullName||`—`)},{label:`الرصيد`,value:r=>money(r.currentBalance)},{label:`الحالة`,value:r=>statusBadge(r.status)}],customers,`لا يوجد عملاء`)}`; }
function debtsPanel(debts, collections){ const open = debts.filter(d=>d.status!==`paid`); return `<div class="actions"><button class="btn" id="exportDebtsBtn">تصدير الذمم</button></div><br>${table([{label:`العميل`,value:`customerName`},{label:`الفاتورة`,value:`invoiceNumber`},{label:`الأصل`,value:r=>money(r.originalAmount)},{label:`المدفوع`,value:r=>money(r.paidAmount)},{label:`المتبقي`,value:r=>money(r.remainingAmount)},{label:`الاستحقاق`,value:`dueDate`},{label:`الحالة`,value:r=>statusBadge(r.status)},{label:`تحصيل`,value:r=>`<button class="btn green" data-collect="${esc(r.id)}">تسجيل تحصيل</button>`}],open,`لا توجد ذمم مفتوحة`)}`; }
function historyPanel(invoices, customers, reps){ return `<div class="actions"><button class="btn" id="exportSalesBtn">تصدير الفواتير</button></div><br>${table([{label:`رقم`,value:`invoiceNumber`},{label:`التاريخ`,value:`date`},{label:`العميل`,value:r=>esc(customers.find(c=>c.id===r.customerId)?.customerName||r.customerName||`—`)},{label:`البائع`,value:r=>esc(reps.find(u=>u.id===r.sellerId)?.fullName||`—`)},{label:`النوع`,value:r=>r.saleType===`cash`?`نقدي`:`ذمم`},{label:`الإجمالي`,value:r=>money(r.total)},{label:`الحالة`,value:r=>statusBadge(r.status)},{label:`طباعة`,value:r=>`<button class="btn" data-print-invoice="${esc(r.id)}">طباعة</button>`}],invoices,`لا توجد فواتير`)}`; }
function customerForm(reps){ return `<form id="customerForm" class="form-grid"><label>اسم العميل<input name="customerName" required></label><label>الهاتف<input name="phone" inputmode="tel"></label><label>المنطقة<input name="area"></label><label>المندوب المسؤول<select name="responsibleRepId">${reps.map(r=>`<option value="${esc(r.id)}">${esc(r.fullName)}</option>`).join(``)}</select></label><label>رصيد افتتاحي<input name="openingBalance" type="number" step="0.001" value="0"></label><label>الحالة<select name="status"><option value="active">فعال</option><option value="inactive">غير فعال</option></select></label><label class="wide">ملاحظات<textarea name="notes"></textarea></label></form>`; }
function bindInvoice(root, items, customers, reps, user){ let lines=[]; const builder=lineBuilder($(`#salesLines`,root),items.filter(i=>i.status===`active`), l=>{lines=l}); $(`#confirmSaleBtn`,root)?.addEventListener(`click`,()=>saveSale(`confirmed`)); $(`#draftSaleBtn`,root)?.addEventListener(`click`,()=>saveSale(`draft`)); async function saveSale(status){ const form=$(`#salesForm`,root); if(!form.reportValidity()) return; if(!lines.length) return toast(`أدخل صنفاً واحداً على الأقل`,`err`); const d=getFormData(form); const seller=await erp.get(`users`,d.sellerId); const warehouseId=seller.assignedWarehouseId || `main`; let total=0; for(const line of lines){ const item=await erp.get(`items`,line.itemId); const available=number(item.stock?.[warehouseId]); if(status===`confirmed` && available<number(line.quantity)) throw new Error(`رصيد غير كاف من ${item.itemName} في مستودع البائع`); total += number(line.quantity)*number(line.price); } const paid=number(d.paidAmount); const remaining=Math.max(0,total-paid); const customer=customers.find(c=>c.id===d.customerId); const invoice=await erp.add(`salesInvoices`,{...d,customerName:customer?.customerName||``,sellerName:seller.fullName,warehouseId,items:lines,total,paidAmount:paid,remainingDebt:remaining,status}); if(status===`confirmed`){ for(const line of lines) await erp.changeStock(line.itemId,warehouseId,-number(line.quantity),`فاتورة بيع`,{invoiceNumber:d.invoiceNumber, invoiceId:invoice.id}); if(d.saleType===`cash`){ await erp.adjustUserBalance(d.sellerId,`cashBalance`,paid || total,`زيادة نقدية من فاتورة بيع`,invoice.id); } else { await erp.add(`customerDebts`,{customerId:d.customerId,customerName:customer?.customerName||``,repId:d.sellerId,invoiceId:invoice.id,invoiceNumber:d.invoiceNumber,originalAmount:total,paidAmount:paid,remainingAmount:remaining,dueDate:d.dueDate,status:remaining>0?`open`:`paid`}); if(paid>0) await erp.adjustUserBalance(d.sellerId,`cashBalance`,paid,`تحصيل جزئي من فاتورة آجلة`,invoice.id); await erp.update(`customers`,d.customerId,{currentBalance:number(customer?.currentBalance)+remaining}); } } toast(status===`draft`?`تم حفظ الفاتورة كمسودة`:`تم اعتماد الفاتورة`); location.reload(); } }
function bindCustomers(root,reps){ root.addEventListener(`click`,async e=>{ if(e.target.closest(`#newCustomerBtn`)){ const {modal}=await import('./utils.js'); modal(`إضافة عميل`,customerForm(reps),[{label:`حفظ`,className:`primary`,handler:async wrap=>{const f=$(`#customerForm`,wrap); if(!f.reportValidity()) return; const d=getFormData(f); await erp.add(`customers`,{...d,openingBalance:number(d.openingBalance),currentBalance:number(d.openingBalance)}); wrap.remove(); toast(`تم حفظ العميل`); location.reload();}}]); } if(e.target.closest(`#exportCustomersBtn`)) exportCSV(`customers.csv`, await erp.list(`customers`)); if(e.target.closest(`#exportSalesBtn`)) exportCSV(`sales.csv`, await erp.list(`salesInvoices`)); if(e.target.closest(`#exportDebtsBtn`)) exportCSV(`customer-debts.csv`, await erp.list(`customerDebts`)); }); }
function bindCollections(root,debts,user){ root.addEventListener(`click`,async e=>{ const btn=e.target.closest(`[data-collect]`); if(!btn) return; const debt=debts.find(d=>d.id===btn.dataset.collect); const {modal}=await import('./utils.js'); modal(`تسجيل تحصيل`, `<form id="collectionForm" class="form-grid two"><label>المبلغ<input name="amount" type="number" min="0.001" step="0.001" max="${number(debt.remainingAmount)}" required></label><label>طريقة الدفع<select name="method"><option value="cash">نقد</option><option value="cliq">CliQ</option></select></label><label class="wide">ملاحظات<textarea name="notes"></textarea></label></form>`,[{label:`حفظ التحصيل`,className:`green`,handler:async wrap=>{const f=$(`#collectionForm`,wrap); if(!f.reportValidity())return; const d=getFormData(f); const amount=number(d.amount); const remaining=number(debt.remainingAmount)-amount; await erp.add(`collections`,{...d,amount,customerDebtId:debt.id,invoiceId:debt.invoiceId,customerId:debt.customerId,repId:debt.repId,date:todayISO(),status:`confirmed`}); await erp.update(`customerDebts`,debt.id,{paidAmount:number(debt.paidAmount)+amount,remainingAmount:remaining,status:remaining<=0?`paid`:`partial`}); const field=d.method===`cliq`?`cliqBalance`:`cashBalance`; await erp.adjustUserBalance(debt.repId,field,amount,`تحصيل من عميل`,debt.id); wrap.remove(); toast(`تم تسجيل التحصيل`); location.reload();}}]); }); }
